version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: gdd/laravel
        container_name: myapp
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: myapp
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - mynet

    nginx:
        container_name: lara-nginx
        image: nginx:alpine
        working_dir: /var/www/html
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./nginx:/etc/nginx/conf.d
        networks:
            - mynet

    db:
        image: postgres
        restart: always
        tty: true
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_DB: slim
            POSTGRES_PASSWORD: sunat
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - mynet

    redis:
        image: redis
        restart: unless-stopped
        command: redis-server --appendonly yes --replica-read-only no
        tty: true
        ports:
            - "6379:6379"
        networks:
            - mynet

#Docker Networks
networks:
    mynet:
        driver: bridge
#Volumes
volumes:
    pgdata:
        driver: local
    esdata:
        driver: local
